class AdsController {
  constructor(model, view) {
    this.model = model;
    this.view = view;
  }

  addAd(title, description, price, imageURL, category) {
    this.model.addAd(title, description, price, imageURL, category);
    this.view.clearInputs();
    this.view.displayAds(this.model.getAllAds());
    this.view.showSuccessMessage();
  }

  deleteAd(id) {
    this.model.deleteAd(id);
    this.view.displayAds(this.model.getAllAds());
  }

  editAd(id, title, description, price, imageURL, category, release) {
    this.model.editAd(
      id,
      title,
      description,
      price,
      imageURL,
      category,
      release
    );
    this.view.displayAds(this.model.getAllAds());
  }
}

const dummy_data = [
  {
    id: 1,
    title: "Huawei",
    description: "Huawei MediaPad T2 7.0",
    release: 2016,
    category: "Phone",
    image: "http://dummyimage.com/157x100.png/5fa2dd/ffffff",
    price: 26284,
  },
  {
    id: 2,
    title: "Allview",
    description: "Allview P7 Xtreme",
    release: 2014,
    category: "Phone",
    image: "http://dummyimage.com/119x100.png/5fa2dd/ffffff",
    price: 114143,
  },
  {
    id: 3,
    title: "Celkon",
    description: "Celkon C44",
    release: 2011,
    category: "Phone",
    image: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
    price: 85618,
  },
  {
    id: 4,
    title: "Panasonic",
    description: "Panasonic P101",
    release: 2018,
    category: "Phone",
    image: "http://dummyimage.com/156x100.png/ff4444/ffffff",
    price: 103877,
  },
  {
    id: 5,
    title: "Sony",
    description: "Sony Ericsson Z320",
    release: 2007,
    category: "Phone",
    image: "http://dummyimage.com/146x100.png/dddddd/000000",
    price: 172241,
  },
  {
    id: 6,
    title: "LG",
    description: "LG KT520",
    release: 2008,
    category: "Phone",
    image: "http://dummyimage.com/122x100.png/cc0000/ffffff",
    price: 78973,
  },
  {
    id: 7,
    title: "Huawei",
    description: "Huawei Ascend G700",
    release: 2013,
    category: "Phone",
    image: "http://dummyimage.com/127x100.png/ff4444/ffffff",
    price: 24293,
  },
  {
    id: 8,
    title: "Lava",
    description: "Lava Iris X1 Atom S",
    release: 2015,
    category: "Phone",
    image: "http://dummyimage.com/211x100.png/cc0000/ffffff",
    price: 165597,
  },
  {
    id: 9,
    title: "Samsung",
    description: "Samsung SGH-500",
    release: 1998,
    category: "Phone",
    image: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
    price: 143185,
  },
  {
    id: 10,
    title: "Micromax",
    description: "Micromax Canvas Selfie 4",
    release: 2016,
    category: "Phone",
    image: "http://dummyimage.com/140x100.png/dddddd/000000",
    price: 61704,
  },
  {
    id: 11,
    title: "Sagem",
    description: "Sagem MW 3026",
    release: 2001,
    category: "Phone",
    image: "http://dummyimage.com/150x100.png/dddddd/000000",
    price: 114979,
  },
  {
    id: 12,
    title: "Plum",
    description: "Plum Bubby",
    release: 2012,
    category: "Phone",
    image: "http://dummyimage.com/114x100.png/dddddd/000000",
    price: 101799,
  },
  {
    id: 13,
    title: "Nokia",
    description: "Nokia 3300",
    release: 2003,
    category: "Phone",
    image: "http://dummyimage.com/113x100.png/dddddd/000000",
    price: 93052,
  },
  {
    id: 14,
    title: "Samsung",
    description: "Samsung Galaxy A42 5G",
    release: 2020,
    category: "Phone",
    image: "http://dummyimage.com/233x100.png/cc0000/ffffff",
    price: 56813,
  },
  {
    id: 15,
    title: "Panasonic",
    description: "Panasonic Eluga L 4G",
    release: 2015,
    category: "Phone",
    image: "http://dummyimage.com/224x100.png/dddddd/000000",
    price: 34506,
  },
  {
    id: 16,
    title: "Volvo",
    description: "940",
    release: 1994,
    category: "Car",
    image: "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
    price: 164353,
  },
  {
    id: 17,
    title: "Cadillac",
    description: "Allante",
    release: 1992,
    category: "Car",
    image: "http://dummyimage.com/117x100.png/5fa2dd/ffffff",
    price: 53834,
  },
  {
    id: 18,
    title: "BMW",
    description: "5 Series",
    release: 1992,
    category: "Car",
    image: "http://dummyimage.com/248x100.png/5fa2dd/ffffff",
    price: 89687,
  },
  {
    id: 19,
    title: "Mitsubishi",
    description: "Tredia",
    release: 1987,
    category: "Car",
    image: "http://dummyimage.com/239x100.png/ff4444/ffffff",
    price: 35293,
  },
  {
    id: 20,
    title: "Jeep",
    description: "Grand Cherokee",
    release: 2003,
    category: "Car",
    image: "http://dummyimage.com/236x100.png/cc0000/ffffff",
    price: 86355,
  },
  {
    id: 21,
    title: "Volkswagen",
    description: "Passat",
    release: 2003,
    category: "Car",
    image: "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
    price: 197893,
  },
  {
    id: 22,
    title: "Alfa Romeo",
    description: "164",
    release: 1994,
    category: "Car",
    image: "http://dummyimage.com/219x100.png/ff4444/ffffff",
    price: 75452,
  },
  {
    id: 23,
    title: "Toyota",
    description: "T100 Xtra",
    release: 1998,
    category: "Car",
    image: "http://dummyimage.com/196x100.png/cc0000/ffffff",
    price: 80570,
  },
  {
    id: 24,
    title: "Chevrolet",
    description: "Suburban 2500",
    release: 2007,
    category: "Car",
    image: "http://dummyimage.com/246x100.png/5fa2dd/ffffff",
    price: 35439,
  },
  {
    id: 25,
    title: "Infiniti",
    description: "QX",
    release: 2010,
    category: "Car",
    image: "http://dummyimage.com/186x100.png/dddddd/000000",
    price: 171882,
  },
  {
    id: 26,
    title: "Plymouth",
    description: "Colt",
    release: 1994,
    category: "Car",
    image: "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
    price: 77053,
  },
  {
    id: 27,
    title: "Cadillac",
    description: "DTS",
    release: 2008,
    category: "Car",
    image: "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
    price: 76130,
  },
  {
    id: 28,
    title: "Mercury",
    description: "Sable",
    release: 2004,
    category: "Car",
    image: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    price: 15107,
  },
  {
    id: 29,
    title: "Kia",
    description: "Forte",
    release: 2011,
    category: "Car",
    image: "http://dummyimage.com/200x100.png/dddddd/000000",
    price: 40059,
  },
  {
    id: 30,
    title: "Toyota",
    description: "Corolla",
    release: 1996,
    category: "Car",
    image: "http://dummyimage.com/201x100.png/dddddd/000000",
    price: 82517,
  },
  {
    id: 31,
    title: "Shire LLC",
    description: "Vyvanse",
    release: 2009,
    category: "Drug",
    image: "http://dummyimage.com/191x100.png/5fa2dd/ffffff",
    price: 35876,
  },
  {
    id: 32,
    title: "Guna spa",
    description: "GUNA-STOMACH",
    release: 1998,
    category: "Drug",
    image: "http://dummyimage.com/187x100.png/ff4444/ffffff",
    price: 16863,
  },
  {
    id: 33,
    title: "REMEDYREPACK INC.",
    description: "Nortriptyline Hydrochloride",
    release: 1963,
    category: "Drug",
    image: "http://dummyimage.com/242x100.png/cc0000/ffffff",
    price: 28181,
  },
  {
    id: 34,
    title: "Welder Services Of Fort Wayne, Inc.",
    description: "OXYGEN",
    release: 2007,
    category: "Drug",
    image: "http://dummyimage.com/139x100.png/dddddd/000000",
    price: 120653,
  },
  {
    id: 35,
    title: "Cardinal Health",
    description: "Risperidone",
    release: 1995,
    category: "Drug",
    image: "http://dummyimage.com/200x100.png/cc0000/ffffff",
    price: 51268,
  },
  {
    id: 36,
    title: "KANEBO COSMETICS INC",
    description: "SENSAI FLUID FINISH FF203",
    release: 1999,
    category: "Drug",
    image: "http://dummyimage.com/186x100.png/dddddd/000000",
    price: 182525,
  },
  {
    id: 37,
    title: "BluePoint Laboratories",
    description: "Amlodipine Besylate and Benazepril Hydrochloride",
    release: 2005,
    category: "Drug",
    image: "http://dummyimage.com/116x100.png/ff4444/ffffff",
    price: 80631,
  },
  {
    id: 38,
    title: "Laboratoires Boiron",
    description: "Children Coldcalm",
    release: 2008,
    category: "Drug",
    image: "http://dummyimage.com/126x100.png/dddddd/000000",
    price: 72117,
  },
  {
    id: 39,
    title: "Physicians Total Care, Inc.",
    description: "Fluocinolone Acetonide",
    release: 2006,
    category: "Drug",
    image: "http://dummyimage.com/110x100.png/cc0000/ffffff",
    price: 51452,
  },
  {
    id: 40,
    title: "Golden State Medical Supply",
    description: "FOSINOPRIL SODIUM",
    release: 2000,
    category: "Drug",
    image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
    price: 22525,
  },
  {
    id: 41,
    title: "Conopco Inc. d/b/a Unilever",
    description: "Suave Fresh",
    release: 1993,
    category: "Drug",
    image: "http://dummyimage.com/166x100.png/dddddd/000000",
    price: 27921,
  },
  {
    id: 42,
    title: "Roxane Laboratories, Inc",
    description: "Meperidine Hydrochloride",
    release: 2005,
    category: "Drug",
    image: "http://dummyimage.com/162x100.png/5fa2dd/ffffff",
    price: 188065,
  },
  {
    id: 43,
    title: "Menper Distributors, Inc.",
    description: "Gesteira",
    release: 1998,
    category: "Drug",
    image: "http://dummyimage.com/213x100.png/dddddd/000000",
    price: 157278,
  },
  {
    id: 44,
    title: "Arbor Pharmaceuticals, Inc.",
    description: "Pediaderm TA",
    release: 1992,
    category: "Drug",
    image: "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
    price: 63709,
  },
  {
    id: 45,
    title: "American Sales",
    description: "Care One",
    release: 2007,
    category: "Drug",
    image: "http://dummyimage.com/163x100.png/ff4444/ffffff",
    price: 96592,
  },
  {
    id: 46,
    title: "Oryx, fringe-eared",
    description: "Oryx gazella callotis",
    release: 1987,
    category: "Animal",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    price: 191236,
  },
  {
    id: 47,
    title: "Bee-eater, carmine",
    description: "Merops nubicus",
    release: 2004,
    category: "Animal",
    image: "http://dummyimage.com/171x100.png/cc0000/ffffff",
    price: 55546,
  },
  {
    id: 48,
    title: "Antelope, four-horned",
    description: "Tetracerus quadricornis",
    release: 2010,
    category: "Animal",
    image: "http://dummyimage.com/126x100.png/5fa2dd/ffffff",
    price: 64859,
  },
  {
    id: 49,
    title: "Crested porcupine",
    description: "Hystrix cristata",
    release: 1999,
    category: "Animal",
    image: "http://dummyimage.com/102x100.png/ff4444/ffffff",
    price: 153834,
  },
  {
    id: 50,
    title: "Civet, common palm",
    description: "Paradoxurus hermaphroditus",
    release: 2010,
    category: "Animal",
    image: "http://dummyimage.com/238x100.png/dddddd/000000",
    price: 165168,
  },
  {
    id: 51,
    title: "Nutcracker, clark's",
    description: "Nucifraga columbiana",
    release: 1996,
    category: "Animal",
    image: "http://dummyimage.com/223x100.png/5fa2dd/ffffff",
    price: 141122,
  },
  {
    id: 52,
    title: "Robin, kalahari scrub",
    description: "Certotrichas paena",
    release: 2006,
    category: "Animal",
    image: "http://dummyimage.com/206x100.png/5fa2dd/ffffff",
    price: 146852,
  },
  {
    id: 53,
    title: "Tortoise, burmese black mountain",
    description: "Manouria emys",
    release: 2012,
    category: "Animal",
    image: "http://dummyimage.com/101x100.png/dddddd/000000",
    price: 122368,
  },
  {
    id: 54,
    title: "Monster, gila",
    description: "Heloderma horridum",
    release: 2002,
    category: "Animal",
    image: "http://dummyimage.com/201x100.png/cc0000/ffffff",
    price: 124539,
  },
  {
    id: 55,
    title: "Rat, white-faced tree",
    description: "Echimys chrysurus",
    release: 2006,
    category: "Animal",
    image: "http://dummyimage.com/122x100.png/ff4444/ffffff",
    price: 71310,
  },
  {
    id: 56,
    title: "Laughing dove",
    description: "Streptopelia senegalensis",
    release: 2008,
    category: "Animal",
    image: "http://dummyimage.com/121x100.png/dddddd/000000",
    price: 51423,
  },
  {
    id: 57,
    title: "Barking gecko",
    description: "Phylurus milli",
    release: 1986,
    category: "Animal",
    image: "http://dummyimage.com/193x100.png/ff4444/ffffff",
    price: 96336,
  },
  {
    id: 58,
    title: "Red-cheeked cordon bleu",
    description: "Uraeginthus bengalus",
    release: 2007,
    category: "Animal",
    image: "http://dummyimage.com/161x100.png/cc0000/ffffff",
    price: 198487,
  },
  {
    id: 59,
    title: "Black-winged stilt",
    description: "Himantopus himantopus",
    release: 1999,
    category: "Animal",
    image: "http://dummyimage.com/245x100.png/ff4444/ffffff",
    price: 30112,
  },
  {
    id: 60,
    title: "Gulls (unidentified)",
    description: "Larus sp.",
    release: 2008,
    category: "Animal",
    image: "http://dummyimage.com/229x100.png/dddddd/000000",
    price: 173753,
  },
];

document.addEventListener("DOMContentLoaded", () => {
  localStorage.setItem("ads", JSON.stringify(dummy_data));
});

const controller = new AdsController(new AdsModel(), new AdsView());
